### ISSUE TITLE
It is showing typing tests

### ISSUE THREAD

**Issue by vinay589** [cooljingle/memrise-all-multiple-choice#2] opened 2018-03-27 09:57 UTC
I have used your script for last 20 days and it is working excellently but today it stopped working and started showing typing tests.
Tried deleting the script and reinstalling it multiple times. Turne off my laptop and chrome also on certain occasions but still the site is showing typing tests. please have a look at it ASAP.

**Comment by cooljingle** [comment] 2018-03-27 19:16
problem was caused by a recent memrise update, should be fixed in v0.0.5

**Closed as completed by cooljingle** 2018-03-27 19:16 UTC
